import json
import pymongo
from ida.code_elements import Serializable, Program


def parser_program_info(json_file):
    """ 
    Parser the instance of Program from the given json file, which 
    is generated by ida pro script
    """
    return Serializable.load(json_file, Program)


def parser_program_info_json(json_file):
    """ 
    Parser the Program into dict from the given json file, which 
    is generated by ida pro script
    """ 
    with open(json_file, 'r') as f:
        return json.load(f)


def load_prog(self, filter):
    pass


def joint(lhs, rhs, c=False):
    """ Joint-product the two given lists """
    rhs = list(rhs)  # in case that rhs is an iterator
    for l in lhs:
        for r in rhs:
            yield [l, r] if c else l + [r]


def joint_list(l):
    """ Reduce the list by applying joint """
    a, c = l[0], True
    for b in l[1:]:
        a = joint(a, b, c)
        c = False
    return a


def flat(lhs, rhs):
    """ Repeat the elem in left up to the size in right """
    for elem, vers in zip(lhs, rhs):
        for ver in vers:
            yield elem, ver


def load_vocab(progs, prog_vers, ccs, cc_vers, opts, obfs):
    # TODO: cache into db
    progs = flat(progs, prog_vers)
    ccs = flat(ccs, cc_vers)

    l = joint_list([progs, ccs, opts, obfs])
    for (prog, prog_ver), (cc, cc_ver), opt, obf in l:
        print(prog, prog_ver, cc, cc_ver, opt, obf)


def test_load_vocab():
    load_vocab(['lua'], [['5', '3']], ['gcc', 'clang'], 
        [['5', '6'], ['9']], ['O0', 'O3'], ['NONE'])
