import json
import pymongo
from src.ida.code_elements import Serializable, Program
from src.utils.list_joint import joint, flat, joint_list


def parser_program_info(json_file):
    """ 
    Parser the instance of Program from the given json file, which 
    is generated by ida pro script
    """
    return Serializable.load(json_file, Program)


def parser_program_info_json(json_file):
    """ 
    Parser the Program into dict from the given json file, which 
    is generated by ida pro script
    """ 
    with open(json_file, 'r') as f:
        return json.load(f)


def load_prog(self, filter):
    pass


def load_vocab(progs, prog_vers, ccs, cc_vers, opts, obfs):
    # TODO: cache into db
    progs = flat(progs, prog_vers)
    ccs = flat(ccs, cc_vers)

    l = joint_list([progs, ccs, opts, obfs])
    for (prog, prog_ver), (cc, cc_ver), opt, obf in l:
        print(prog, prog_ver, cc, cc_ver, opt, obf)


def test_load_vocab():
    load_vocab(['lua'], [['5', '3']], ['gcc', 'clang'], 
        [['5', '6'], ['9']], ['O0', 'O3'], ['NONE'])
